"""Add index on long_url column

Revision ID: add_index_long_url
Revises: 546bab5309e8
Create Date: 2026-01-29 20:26:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_index_long_url'
down_revision: Union[str, None] = '546bab5309e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_short_urls_long_url'), 'short_urls', ['long_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_urls_long_url'), table_name='short_urls')
    # ### end Alembic commands ###
